### PR TITLE
Fix ;)

### PR DESCRIPTION
**Pull request by SakataGintokiYT**

### CODE REVIEW

**Comment by Zangetsu38** [comment]
please don't fork my git, use git master here for this https://github.com/RPCS3/rpcs3 :)

**Comment by SakataGintokiYT** [comment]
Can you delete this ? sorry ;P

**Comment by Zangetsu38** [comment]
not worry :)

**Comment by SakataGintokiYT** [comment]
Still black screen :P
Fotoszok.pl
Fotoszok.pl

DX12 ^_^
Fotoszok.pl

**Comment by Zangetsu38** [comment]
yes, i know

**Pull request closed without merging**
